name: user_profile_avatar
description: A simple widget that display round profile picture and display native circular progress indicator whilst image is being fetched.
homepage: https://github.com/zeshanghayoomi/flutter_user_profile_avatar
version: 0.0.10

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/user_profile_avatar/src/local_assets/icons/user_empty_avatar.png

