name: user_profile_avatar
description: A simple widget that display round profile picture where the picture is fetched from network and displays circular progress indicator whilst the image is being loaded. Also, has the ability to display notification bubble.
version: 0.0.3
homepage: https://github.com/zeshanghayoomi/flutter_user_profile_avatar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/user_profile_avatar/local/icons/user_empty_avatar.png

